SELECT *
FROM person.Person;

SELECT Title
FROM person.person;

-- PARA VER TODOS OS EMAILS DA TABELA
SELECT *
FROM person.EmailAddress;

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA
SELECT FirstName, LastName
FROM person.Person;

-- PARA VER SOMENTE OS PRIMEIRO DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName
FROM person.Person

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName, LastName
FROM person.Person;

-- SE EU QUISER VER SOMENTE OS PRODUTOS QUE TENHAM A COR AZUL OU VERMELHA
SELECT *
FROM Production.Product
WHERE color = 'blue' or color = 'black';

-- SE EU QUISER VER OS VALORES DE 1500 A 5000
SELECT *
FROM Production.Product
WHERE ListPrice > 1500 and ListPrice < 5000;

-- SE EU NAO QIUISER VER NENHUM PRODUTO QUE SEJA VERMELHO
SELECT *
FROM Production.Product
WHERE color <> 'red';

-- DESAFIO 1 =  A EQUIPE DE PRODUCAO PRECISA DO NOME DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500KG MAS NAO MAIS QUE 700KG PARA INSPEÇÃO

SELECT *
FROM Production.Product
WHERE Weight > 500 and Weight < 750;

-- DESAFIO 2 = FOI PEDIDO PELO MARKETING UM RELACAO DE TODOS OS EMPREGADOS(EMPLOYEES) QUE SAO CASADOS(SINGLE=SOLTEIRO, MARRIED=CASADO) E SAO ASALARIADOS(SALIED)

SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'm' AND SalariedFlag = 1;


-- DESAFIO 3 = ACHAR UM USUARIO CHAMADO PETER KREBS QUE ESTA DEVENDO UM PAGAMENTO, CONSIGA O EMAIL PARA QUE POSSAMOS ENVIAR UMA COBRANÇA, (USAR A TABELA PERSON.PERSON E DEPOIS A TABELA PERSON.EMAILADREES)

SELECT *
FROM person.Person
WHERE FirstName = 'Peter' and LastName = 'Krebs';

SELECT *
FROM person.EmailAddress
WHERE BusinessEntityID = 26;

SELECT count(DISTINCT Title)
FROM person.Person;

-- DESAFIO 1 = SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS (PRODUCTION.PRODUCT)

SELECT count(*)
FROM Production.Product;

-- DESAFIO 2 QUANTOS TAMANHOS DE PRODUTOS CADASTRADOS NA TABELA

SELECT count(Size)
FROM Production.Product;


SELECT TOP 10 *
FROM Production.Product;

--  DESAFIO 1 ORDER BY = OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO AO MAIS BARATO

SELECT *
FROM Production.Product;

SELECT TOP 10 ProductID
FROM Production.Product
ORDER BY listprice desc;

-- DESAFIO 2 = OBTER O NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O PRODUCTID ENTRE 1 ~ 4

SELECT TOP 4 name, ProductNumber
FROM Production.Product
ORDER BY ProductID;



