SELECT *
FROM person.Person;

SELECT Title
FROM person.person;

-- PARA VER TODOS OS EMAILS DA TABELA
SELECT *
FROM person.EmailAddress;

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA
SELECT FirstName, LastName
FROM person.Person;

-- PARA VER SOMENTE OS PRIMEIRO DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName
FROM person.Person

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName, LastName
FROM person.Person;

-- SE EU QUISER VER SOMENTE OS PRODUTOS QUE TENHAM A COR AZUL OU VERMELHA
SELECT *
FROM Production.Product
WHERE color = 'blue' or color = 'black';

-- SE EU QUISER VER OS VALORES DE 1500 A 5000
SELECT *
FROM Production.Product
WHERE ListPrice > 1500 and ListPrice < 5000;

-- SE EU NAO QIUISER VER NENHUM PRODUTO QUE SEJA VERMELHO
SELECT *
FROM Production.Product
WHERE color <> 'red';

-- DESAFIO 1 =  A EQUIPE DE PRODUCAO PRECISA DO NOME DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500KG MAS NAO MAIS QUE 700KG PARA INSPEÇÃO

SELECT *
FROM Production.Product
WHERE Weight > 500 and Weight < 750;

-- DESAFIO 2 = FOI PEDIDO PELO MARKETING UM RELACAO DE TODOS OS EMPREGADOS(EMPLOYEES) QUE SAO CASADOS(SINGLE=SOLTEIRO, MARRIED=CASADO) E SAO ASALARIADOS(SALIED)

SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'm' AND SalariedFlag = 1;


-- DESAFIO 3 = ACHAR UM USUARIO CHAMADO PETER KREBS QUE ESTA DEVENDO UM PAGAMENTO, CONSIGA O EMAIL PARA QUE POSSAMOS ENVIAR UMA COBRANÇA, (USAR A TABELA PERSON.PERSON E DEPOIS A TABELA PERSON.EMAILADREES)

SELECT *
FROM person.Person
WHERE FirstName = 'Peter' and LastName = 'Krebs';

SELECT *
FROM person.EmailAddress
WHERE BusinessEntityID = 26;


SELECT count(DISTINCT Title)
FROM person.Person;

-- DESAFIO 1 = SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS (PRODUCTION.PRODUCT)

SELECT count(*)
FROM Production.Product;

-- DESAFIO 2 QUANTOS TAMANHOS DE PRODUTOS CADASTRADOS NA TABELA

SELECT count(Size)
FROM Production.Product;


SELECT TOP 10 *
FROM Production.Product;

--  DESAFIO 1 ORDER BY = OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO AO MAIS BARATO

SELECT *
FROM Production.Product;

SELECT TOP 10 ProductID
FROM Production.Product
ORDER BY listprice desc;

-- DESAFIO 2 = OBTER O NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O PRODUCTID ENTRE 1 ~ 4

SELECT TOP 4 name, ProductNumber
FROM Production.Product
ORDER BY ProductID;

git add .
git commit -m "update"
git push

-- FILTRAGEM DE VALOR ATÉ TAL VALOR "valor >= minimo and valor <= maximo;"
SELECT * 
FROM Production.Product
WHERE ListPrice between 1000 and 1500;

SELECT * 
FROM Production.Product
WHERE ListPrice NOT BETWEEN 1000 and 1500;

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' and '2010/01/01'
ORDER BY HireDate

-- OPERADOR "IN" JUNTAMENTE COM WHERE PARA VERIFICAR SE O VALOR CORRESPONDE COM QUALQUER VALOR NA LISTA DE VALORES;

SELECT *
FROM Person.Person
WHERE BusinessEntityID IN (2,7,13);

-- DESAFIO DE ACHAR ALGUMA PESSOA DA QUAL NÃO SE LEMBRA O NOME AO CERTO, MAIS SABE QUE O NOME ERA "OVI..." ALGUMA COISA.

SELECT*
FROM Person.Person
WHERE FirstName LIKE 'ovi%';

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%to'; -- % no começo para recordar de uma parte final do nome

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%vane%'; --% no meio para recordar de uma parte do meio do nome

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%ro_'; -- 1 caracte após o "ro"

-- DESAFIO FUNDAMENTOS SQL ATÉ AGORA
-- 1 = QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA  QUE CUSTAM MAIS QUE 1500 DOLARES?


SELECT count(ListPrice)
FROM Production.Product
WHERE ListPrice >= 1500;

-- 2 = QUANTAS PÉSSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P 

SELECT LastName
FROM Person.Person
WHERE LastName LIKE 'P%';

SELECT COUNT(LastName)
FROM Person.Person
WHERE LastName LIKE 'P%';

-- 3 = EM QUANTAS CIDADES UNICAS ESTAO CADASTRADOS OS NOSSSOS CLIENTES

SELECT COUNT(DISTINCT City)
FROM Person.Address;

-- 4 = QUAIS SAO AS CIDADES UNICAS QUE TEMOS CADASTRADOS EM NOSSO SISTEMA

SELECT DISTINCT (City)
FROM Person.Address;

-- 5 = QUANTOS PRODUTOS VERMELHOS TEM PRECO ENTRE 500 A 1000 DOLARES

SELECT COUNT(*)
FROM Production.Product
WHERE color = 'RED'
AND ListPrice BETWEEN 500 and 1000;

-- 6 = QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'ROAD' NO NOME DELES

SELECT COUNT(*)
FROM Production.Product
WHERE Name LIKE '%road%';

SELECT (Name)
FROM Production.Product
WHERE Name LIKE '%road%';
