SELECT *
FROM person.Person;

SELECT Title
FROM person.person;

-- PARA VER TODOS OS EMAILS DA TABELA
SELECT *
FROM person.EmailAddress;

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA
SELECT FirstName, LastName
FROM person.Person;

-- PARA VER SOMENTE OS PRIMEIRO DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName
FROM person.Person

-- PARA VER TODOS OS NOMES E SOBRENOMES DA TABELA SEM DUPLICACAO
SELECT DISTINCT FirstName, LastName
FROM person.Person;

-- SE EU QUISER VER SOMENTE OS PRODUTOS QUE TENHAM A COR AZUL OU VERMELHA
SELECT *
FROM Production.Product
WHERE color = 'blue' or color = 'black';

-- SE EU QUISER VER OS VALORES DE 1500 A 5000
SELECT *
FROM Production.Product
WHERE ListPrice > 1500 and ListPrice < 5000;

-- SE EU NAO QIUISER VER NENHUM PRODUTO QUE SEJA VERMELHO
SELECT *
FROM Production.Product
WHERE color <> 'red';

-- DESAFIO 1 =  A EQUIPE DE PRODUCAO PRECISA DO NOME DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500KG MAS NAO MAIS QUE 700KG PARA INSPEÇÃO

SELECT *
FROM Production.Product
WHERE Weight > 500 and Weight < 750;

-- DESAFIO 2 = FOI PEDIDO PELO MARKETING UM RELACAO DE TODOS OS EMPREGADOS(EMPLOYEES) QUE SAO CASADOS(SINGLE=SOLTEIRO, MARRIED=CASADO) E SAO ASALARIADOS(SALIED)

SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'm' AND SalariedFlag = 1;


-- DESAFIO 3 = ACHAR UM USUARIO CHAMADO PETER KREBS QUE ESTA DEVENDO UM PAGAMENTO, CONSIGA O EMAIL PARA QUE POSSAMOS ENVIAR UMA COBRANÇA, (USAR A TABELA PERSON.PERSON E DEPOIS A TABELA PERSON.EMAILADREES)

SELECT *
FROM person.Person
WHERE FirstName = 'Peter' and LastName = 'Krebs';

SELECT *
FROM person.EmailAddress
WHERE BusinessEntityID = 26;


SELECT count(DISTINCT Title)
FROM person.Person;

-- DESAFIO 1 = SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS (PRODUCTION.PRODUCT)

SELECT count(*)
FROM Production.Product;

-- DESAFIO 2 QUANTOS TAMANHOS DE PRODUTOS CADASTRADOS NA TABELA

SELECT count(Size)
FROM Production.Product;


SELECT TOP 10 *
FROM Production.Product;

--  DESAFIO 1 ORDER BY = OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO AO MAIS BARATO

SELECT *
FROM Production.Product;

SELECT TOP 10 ProductID
FROM Production.Product
ORDER BY listprice desc;

-- DESAFIO 2 = OBTER O NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O PRODUCTID ENTRE 1 ~ 4

SELECT TOP 4 name, ProductNumber
FROM Production.Product
ORDER BY ProductID;

git add .
git commit -m "update"
git push

-- FILTRAGEM DE VALOR ATÉ TAL VALOR "valor >= minimo and valor <= maximo;"
SELECT * 
FROM Production.Product
WHERE ListPrice between 1000 and 1500;

SELECT * 
FROM Production.Product
WHERE ListPrice NOT BETWEEN 1000 and 1500;

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' and '2010/01/01'
ORDER BY HireDate

-- OPERADOR "IN" JUNTAMENTE COM WHERE PARA VERIFICAR SE O VALOR CORRESPONDE COM QUALQUER VALOR NA LISTA DE VALORES;

SELECT *
FROM Person.Person
WHERE BusinessEntityID IN (2,7,13);

-- DESAFIO DE ACHAR ALGUMA PESSOA DA QUAL NÃO SE LEMBRA O NOME AO CERTO, MAIS SABE QUE O NOME ERA "OVI..." ALGUMA COISA.

SELECT*
FROM Person.Person
WHERE FirstName LIKE 'ovi%';

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%to'; -- % no começo para recordar de uma parte final do nome

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%vane%'; --% no meio para recordar de uma parte do meio do nome

SELECT*
FROM Person.Person
WHERE FirstName LIKE '%ro_'; -- 1 caracte após o "ro"

-- DESAFIO FUNDAMENTOS SQL ATÉ AGORA
-- 1 = QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA  QUE CUSTAM MAIS QUE 1500 DOLARES?


SELECT count(ListPrice)
FROM Production.Product
WHERE ListPrice >= 1500;

-- 2 = QUANTAS PÉSSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P 

SELECT LastName
FROM Person.Person
WHERE LastName LIKE 'P%';

SELECT COUNT(LastName)
FROM Person.Person
WHERE LastName LIKE 'P%';

-- 3 = EM QUANTAS CIDADES UNICAS ESTAO CADASTRADOS OS NOSSSOS CLIENTES

SELECT COUNT(DISTINCT City)
FROM Person.Address;

-- 4 = QUAIS SAO AS CIDADES UNICAS QUE TEMOS CADASTRADOS EM NOSSO SISTEMA

SELECT DISTINCT (City)
FROM Person.Address;

-- 5 = QUANTOS PRODUTOS VERMELHOS TEM PRECO ENTRE 500 A 1000 DOLARES

SELECT COUNT(*)
FROM Production.Product
WHERE color = 'RED'
AND ListPrice BETWEEN 500 and 1000;

-- 6 = QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'ROAD' NO NOME DELES

SELECT COUNT(*)
FROM Production.Product
WHERE Name LIKE '%road%';

SELECT (Name)
FROM Production.Product
WHERE Name LIKE '%road%';

-- FUNCOES DE AGREGAÇÃO

SELECT TOP 10 SUM (LineTotal) AS "SOMA"
FROM Sales.SalesOrderDetail;

SELECT TOP 10 MIN (LineTotal) AS "MIN"
FROM Sales.SalesOrderDetail;

SELECT TOP 10 MAX (LineTotal) AS "MAX"
FROM Sales.SalesOrderDetail;


SELECT TOP 10 AVG (LineTotal) AS "MEDIA"
FROM Sales.SalesOrderDetail;

-- GROUP BY + AGREGACAO

SELECT *
FROM SALES.SalesOrderDetail

SELECT SpecialOfferID, SUM (UnitPrice) AS "SOMA"
FROM SALES.SalesOrderDetail
GROUP BY SpecialOfferID;

SELECT SpecialOfferID, UnitPrice
FROM sales.SalesOrderDetail
WHERE SpecialOfferID = 9;

-- QUANTO DE CADA PRODUTO FOI VENDIDO ATE HOJE

SELECT * FROM SALES.SalesOrderDetail

SELECT ProductID, COUNT(ProductID) AS "CONTAGEM"
FROM SALES.SalesOrderDetail
GROUP BY ProductID

-- QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS EM NOSSO BANCO DE DADOS

SELECT FirstName, COUNT(FirstName) AS "CONTAGEM"
FROM Person.Person
GROUP BY FirstName;


-- NA TABELA PRODUCTIO.PRODUCT QUERO SABER  A MEDIA DE PRECO PARA OS PRODUTOS QUE SAO PRATAS (SILVER)

SELECT *
FROM Production.Product


SELECT Color, AVG(ListPrice) AS "PRECO"
FROM Production.Product
WHERE Color = 'Silver'
GROUP BY Color

-- DESAFIO 1 = QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR O MIDDLENAME

SELECT *
FROM PERSON.Person

SELECT MiddleName, COUNT(MiddleName) AS "QUANTIDADE"
FROM Person.Person
GROUP BY MiddleName;

-- DESAFIO 2 = EU PRECISO SABER EM MEDIA QUAL É A QUANTIDADE(QUANTITY) QUE CADA PRODUTO É VENDIDO NA LOJA

SELECT *
FROM SALES.SalesOrderDetail

SELECT ProductID, AVG(OrderQty) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID;

-- DESAFIO 3 = QUAL FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA(lINETOTAL) POR PRODUTO DO MAIOR VALOR PARA O MENOR

SELECT *
FROM Sales.SalesOrderDetail

SELECT TOP 10 ProductID, SUM(LineTotal) AS "VENDAS"
FROM sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) desc;


-- DESAFIO 4 = EU PRECISO SABER QUANTOS PRODUTOS E QUAL A QUANTIDADE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS NOSSAS ORDEM DE SERVICO(WorkOrder), AGRUPADOS POR ProductId

SELECT *
FROM Production.WorkOrder

SELECT ProductID, COUNT (ProductID) AS "CONTAGEM",
AVG (OrderQty) AS "MEDIA"
FROM Production.WorkOrder
GROUP BY ProductID


-- HAVING (USADO MUITO USADO EM JUNÇÃO COM O GROUP BY PARA FILTRAR RESULTADOS)

/* SELECT coluna1, FuncaoAgregacao(Coluna2)
FROM nomeTabela
GROUP BY coluna1
HAVING codicao;

DIFERENÇA ENTRE HAVING E WHERE É QUE O GROUP BY É APLICADO DEPOIS QUE OS DADOS JA FORAM AGRUPADOS, ENQUANTO O WHERE É APLICADO ANTES DOS DADOS SEREM AGRUPADOS.
*/


-- quero saber todas as pessoas que são maior de idade
SELECT FirstName, COUNT (FirstName) AS "QUANTIDADE"
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 18;

-- quero saber quais produtos que no total de vendas estao em entre 162k a 500k

SELECT TOP 10 *
FROM SALES.SalesOrderDetail

SELECT ProductID, SUM(LineTotal) AS "TOTAL"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000;
 

 -- QUERO SABER QUAIS NOMES NO SISTEMA TEM OCORRENCIA MAIOR QUE 10 VEZES POREM ONDE O TITULO É "MR"

SELECT FirstName, COUNT (FirstName) AS "QUANTIDADE"
FROM Person.Person
WHERE Title = 'Mr.'
GROUP BY FirstName
HAVING COUNT(Title) > 10;

/* DESAFIO 1 = ESTAMOS QUERENDO IDENTIFICAR AS PROVINCIAS(stateProvinceID) COM O MAIOR NUMERO DE CADASTRADOS DO NOSSO SISTEMA, ENTÃO É PRECISO ENCONTRAR QUAIS PROVINCIAS
(stateProvinceID) ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS QUE 1000 VEZES.
*/

SELECT *
FROM Person.Address

SELECT COUNT(StateProvinceID) AS "QUANTIDADE"
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000;


/* DESAFIO 2 = SENDO QUE SE TRATA DE UMA MULTINACIONAL OS GERENTES QUEREM SABER QUAIS PRODUTOS (ProductID) NAO ESTAO TRAZENDO EM MEDIA NO MINIMO 1 MILHÃO DE VENDAS
(LineTotal)
*/

SELECT *
FROM Sales.SalesOrderDetail

SELECT ProductID, AVG(LineTotal) AS "MEDIA" -- SELECIONO O PRODUTO E A MEDIA DO VALOR TOTAL
FROM SALES.SalesOrderDetail -- DA TABELA
GROUP BY ProductID -- AGRUPANDO PELO PRODUTO
HAVING AVG(LineTotal) < 1000000; -- ONDE A MEDIA DO VALOR TOTAL SEJA NO MINIMO 1 MILHÃO
